### ISSUE TITLE
Edit Widget

### ISSUE THREAD

**Issue by ixlipixli** [albatrossdigital/widgetbootstrap#2]
Hi,
I have some problems to edit the widget. If I have a picture and text in one column its almost impossible to click at them seperately.

Is there a trick?

**Comment by jlyon** [comment]
Could you post the version of CKEditor you're using and a screenshot of the issue?  Thanks!

**Comment by ixlipixli** [comment]
Thank you for your reply!
I am using CKEditor 4.
It's impossible for me to select a word and edit it. When I try to click on it it marks the whole content, the widget or one column. And the mousecursor doesn't work in the widget like in normal text.

Thank you for your help!


![screenshot_1](https://cloud.githubusercontent.com/assets/13272867/9106157/666cbce8-3c1e-11e5-9b56-12f1c87d2ebb.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/13272867/9106156/666a5dfe-3c1e-11e5-976c-477cd0af4661.jpg)
![screenshot_3](https://cloud.githubusercontent.com/assets/13272867/9106155/666a61aa-3c1e-11e5-9632-78008beadb8f.jpg)

**Comment by ixlipixli** [comment]
I installed Firefox again and since then its working perfectly.
I guess something went wrong there (or with firebug)!

**Comment by jlyon** [comment]
Hmm. Thanks for following up!
